In [2]:
import math
math.factorial(8)

40320

In [4]:
factorial_new = math.factorial #creates new function that's the same as math.factorial
factorial_new(8)


40320

In [6]:
from math import factorial
factorial(8)
#DON'T DO: from math import *

40320

In [8]:
import numpy as np
#gives you vectorized operations

In [10]:
a = [1,2,3,4]
b = np.array(a)

In [11]:
b

array([1, 2, 3, 4])

In [12]:
b.ndim

1

In [13]:
b.shape

(4,)

In [14]:
b.dtype

dtype('int64')

In [15]:
a = [1.,2.,3.,4.]
b = np.array(a)

In [16]:
b.dtype

dtype('float64')

In [17]:
np.zeros(5)
#array of all 0's

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.randint(1,100)

23

In [22]:
c = np.random.normal(size = (4,4))

In [23]:
c

array([[ 0.50599722, -0.99547168, -1.20601483, -0.92439843],
       [-0.21956265,  0.89821953,  0.38261401, -0.16585284],
       [ 1.29538774,  1.08444705,  1.62051162,  0.31667333],
       [ 1.1627217 ,  0.88096051,  0.34488154, -0.07751288]])

In [24]:
np.random.normal? #this calls the help menu

In [25]:
c[1][1] #second row, second column element

0.89821952679373995

In [26]:
c[1:3] #gives you rows 1 and 2 (python goes up to but not including)


array([[-0.21956265,  0.89821953,  0.38261401, -0.16585284],
       [ 1.29538774,  1.08444705,  1.62051162,  0.31667333]])

In [27]:
c[:2,:2]

array([[ 0.50599722, -0.99547168],
       [-0.21956265,  0.89821953]])

In [30]:
d = np.array([[1.,2.,3.],[4.,5.,6.]])

In [31]:
d*d

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [34]:
#to get all the columns
a = c[:,1]

In [35]:
b = c[:,1].T

In [36]:
a.shape

(4,)

In [42]:
b.shape

(4,)

In [43]:
from numpy.linalg import inv,det

In [45]:
j = np.array([[1.,2.],[3.,4.]])
j

array([[ 1.,  2.],
       [ 3.,  4.]])

j

In [46]:
j*j

array([[  1.,   4.],
       [  9.,  16.]])

In [47]:
j-j

array([[ 0.,  0.],
       [ 0.,  0.]])

In [48]:
j ** 0.5

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [49]:
j*2

array([[ 2.,  4.],
       [ 6.,  8.]])

In [51]:
#matrix multiplication
j.dot(j)

array([[  7.,  10.],
       [ 15.,  22.]])

In [52]:
f = np.array([1,2,3,4,1])

In [53]:
f.sort()

In [54]:
f #by sorting, we've actually changed the array

array([1, 1, 2, 3, 4])

In [55]:
f = np.array([1,2,3,4,1])

In [56]:
np.sort(f)

array([1, 1, 2, 3, 4])

In [57]:
f

array([1, 2, 3, 4, 1])

In [58]:
%time np.sort(f)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 619 µs


array([1, 1, 2, 3, 4])

In [59]:
%timeit np.sort(f)

The slowest run took 83.57 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.79 µs per loop


# Classes (7-14-16)

Class defines different types objects and the various functions ("methods") that can act on them

'init' and 'str' methods:

For every new class object, it needs an init function

In [1]:
class Pet(object):
        def __init__(self, name, species):
            self.name = name
            self.species = species
        def getName(self):
                return self.name
            
        def getSpecies(self):
                return self.species
        def __str__(self):
                return '%s is a %s' % (self.name, self.species)
            
        

In [2]:
mycat = Pet('Odafin', 'Cat')

In [3]:
mycat.getName()

'Odafin'

In [4]:
Pet.getName(mycat)

'Odafin'

## Subclasses

Subclasses inherit everything from it's parent class, unless otherwise specified ("overridden")

In [5]:
class Cat(Pet):
        def __init__(self, name, fluffy):
            Pet.__init__(self, name, 'Cat')
            self.fluffy = fluffy
        def isFluffy(self):
            return self.fluffy

In [6]:
pet1 = Pet('Max', 'Cat')

In [9]:
cat1 = Cat('Max', 4)

In [10]:
isinstance(pet1,Pet)

True

In [11]:
isinstance(cat1,Pet)

True

In [13]:
pet1.isFluffy()
#this should fail, pets doesn't have attribute fluffy

AttributeError: 'Pet' object has no attribute 'isFluffy'

In [14]:
pet1.getName()

'Max'

In [15]:
dir(cat1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'fluffy',
 'getName',
 'getSpecies',
 'isFluffy',
 'name',
 'species']

####Magic methods

Really important methods (ex: init and str)

"Dunder" methods: you don't have to invoke them; they are invoked automatically

"from pets import Pet"; where pets.py is the python file with all the classes and methods

NameError: name 'prop' is not defined

In [ ]:
properties = prop(cat1)